### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by ajendrosch**
upgraded libraries (on the feat/enable_http_headers branch. Now the build should work).

### CODE REVIEW

**Review by ajendrosch — COMMENTED** [review]
http headers working similar to curl. The http-header parameter can be set multiple times. Libraries upgraded.

**Comment by ajendrosch** [comment]
**Call**:
go run cmd/collector/main.go \
    --storage="api" \
    --environment-name=test \
    --debug=true \
    --api-endpoint=http://localhost:8080/ \
    --http-header="X-Api-Key:secret" \
    --http-header="Authorization:Bearer :1,2.3;4-5'6" \
    --api-key="56789" \
    --api-signature="890"

**Result**:
PUT / HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 24313
Authorization: Bearer :1,2.3;4-5'6
Content-Type: application/json
X-Api-Key: secret
X-Api-Signature: 890
Accept-Encoding: gzip

**Review by ajendrosch — COMMENTED** [review]
added log message for success

**Review by ajendrosch — COMMENTED** [review]
ok

**Review by ChristianSpiess — APPROVED** [review]

**Pull request merged**
